    
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import pickle




# Parameters to use
# source address
# destination address
# age of driver
# age of vehicle
# rainfall amount
# time of day

# Parameters to be defined by user : all except rainfall and time of day
print("1")
num_accident_locations = ctrl.Antecedent(np.arange(0,18,1), 'num_accident_locations')
age_of_driver = ctrl.Antecedent(np.arange(18,90,1), 'age_of_driver')
age_of_vehicle = ctrl.Antecedent(np.arange(0,40,1), 'age_of_vehicle')
rainfall = ctrl.Antecedent(np.arange(0,100,1), 'rainfall')
time_of_day = ctrl.Antecedent(np.arange(0, 24, 1), 'time_of_day')
print("2")
age_of_driver['young'] = fuzz.trimf(age_of_driver.universe, [18, 18, 35])
age_of_driver['adult'] = fuzz.trimf(age_of_driver.universe, [30, 40, 50])
age_of_driver['aged'] = fuzz.trimf(age_of_driver.universe, [45, 55, 65])
age_of_driver['senior'] = fuzz.trimf(age_of_driver.universe, [60, 90, 90])
print("3")
time_of_day['morning'] = fuzz.trimf(time_of_day.universe, [5, 9, 12])  
time_of_day['afternoon'] = fuzz.trimf(time_of_day.universe, [11, 14, 17]) 
time_of_day['evening'] = fuzz.trimf(time_of_day.universe, [16, 19, 22])  
time_of_day['night'] = fuzz.trimf(time_of_day.universe, [20, 23, 24])  

age_of_vehicle['new'] = fuzz.trimf(age_of_vehicle.universe, [0, 0, 10]) 
age_of_vehicle['moderate'] = fuzz.trimf(age_of_vehicle.universe, [8, 15, 22]) 
age_of_vehicle['old'] = fuzz.trimf(age_of_vehicle.universe, [20, 40, 40])  

print("4")
num_accident_locations['low'] = fuzz.trimf(num_accident_locations.universe, [0, 0, 20]) 
num_accident_locations['medium'] = fuzz.trimf(num_accident_locations.universe, [15, 30, 40])  
num_accident_locations['high'] = fuzz.trimf(num_accident_locations.universe, [35, 100, 100])  

rainfall['low'] = fuzz.trimf(rainfall.universe, [0, 0, 40])  
rainfall['medium'] = fuzz.trimf(rainfall.universe, [30, 50, 70])  
rainfall['high'] = fuzz.trimf(rainfall.universe, [60, 100, 100])  
print("5")
rainfall.view()
time_of_day.view()
accident_probability = ctrl.Consequent(np.arange(0,1.00001,0.00001), 'Accident Probability')
accident_probability['low'] = fuzz.trimf(accident_probability.universe, [0, 0, 0.2])
accident_probability['medium'] = fuzz.trimf(accident_probability.universe, [0.15, 0.35, 0.5])
accident_probability['high'] = fuzz.trimf(accident_probability.universe, [0.4, 1, 1])
print("6")
accident_probability.view()

rule1 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule2 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule3 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule4 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule5 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule6 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule7 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule8 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule9 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule10 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule11 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule12 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule13 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule14 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule15 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule16 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule17 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule18 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule19 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule20 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule21 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['low']&rainfall['high'], accident_probability['low'])
rule22 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule23 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule24 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule25 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule26 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule27 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule28 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule29 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule30 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['low']&rainfall['high'], accident_probability['low'])
rule31 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule32 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule33 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule34 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule35 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule36 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])

rule37 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])

rule38 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule39 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule40 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule41 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule42 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule43 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule44 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule45 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule46 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule47 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['medium'], accident_probability['medium'])
rule48 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule49 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule50 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule51 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['high'], accident_probability['high'])
rule52 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule53 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule54 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule55 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule56 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule57 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule58 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule59 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule60 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule61 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule62 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule63 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule64 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule65 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule66 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule67 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule68 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule69 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule70 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule71 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule72 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])

rule73 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule74 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['low']&rainfall['medium'], accident_probability['medium'])
rule75 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['low']&rainfall['high'], accident_probability['high'])
rule76 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule77 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule78 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['medium']&rainfall['high'], accident_probability['high'])
rule79 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule80 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule81 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule82 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule83 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['medium'], accident_probability['medium'])
rule84 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['high'], accident_probability['high'])
rule85 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['low'], accident_probability['medium'])
rule86 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['medium'], accident_probability['high'])
rule87 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['high'], accident_probability['high'])
rule88 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule89 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule90 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule91 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule92 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule93 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule94 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule95 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule96 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule97 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule98 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule99 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule100 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule101 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule102 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule103 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule104 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule105 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule106 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule107 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule108 = ctrl.Rule(age_of_driver['young']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])

rule109 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule110 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule111 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['low']&rainfall['high'], accident_probability['low'])
rule112 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule113 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule114 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule115 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule116 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule117 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['high']&rainfall['high'], accident_probability['medium'])
rule118 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule119 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule120 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule121 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule122 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule123 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule124 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule125 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule126 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule127 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule128 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule129 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['low']&rainfall['high'], accident_probability['low'])
rule130 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule131 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule132 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule133 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule134 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule135 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule136 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule137 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule138 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule139 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule140 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule141 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule142 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule143 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule144 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])

rule145 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule146 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule147 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['low']&rainfall['high'], accident_probability['low'])
rule148 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule149 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['medium']&rainfall['medium'], accident_probability['low'])
rule150 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule151 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule152 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule153 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['high']&rainfall['high'], accident_probability['medium'])
rule154 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule155 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule156 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['high'], accident_probability['low'])
rule157 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule158 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule159 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule160 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule161 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule162 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule163 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule164 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule165 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['low']&rainfall['high'], accident_probability['low'])
rule166 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule167 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['medium']&rainfall['medium'], accident_probability['low'])
rule168 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule169 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule170 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule171 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['high']&rainfall['high'], accident_probability['medium'])
rule172 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule173 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule174 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['low']&rainfall['high'], accident_probability['low'])
rule175 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule176 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule177 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule178 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule179 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule180 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])

rule181 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule182 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule183 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule184 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule185 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['medium']&rainfall['medium'], accident_probability['low'])
rule186= ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule187 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule188 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule189 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule190 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule191 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule192 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule193 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule194 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule195 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule196 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule197 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule198 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule199 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule200 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule201 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['low']&rainfall['high'], accident_probability['low'])
rule202 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule203 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule204 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule205 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule206 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule207 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule208 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule209 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule210 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule211 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule212 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule213 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule214 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule215 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule216 = ctrl.Rule(age_of_driver['adult']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])


rule217 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule218 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule219 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['low']&rainfall['high'], accident_probability['low'])
rule220 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule221 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['medium']&rainfall['medium'], accident_probability['low'])
rule222 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule223 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule224 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule225 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['high']&rainfall['high'], accident_probability['medium'])
rule226 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule227 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule228 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule229 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule230 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['medium'], accident_probability['low'])
rule231 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule232 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule233 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule234 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule235 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule236 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule237 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['low']&rainfall['high'], accident_probability['low'])
rule238 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule239 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['medium']&rainfall['medium'], accident_probability['low'])
rule240 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule241 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule242 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule243 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['high']&rainfall['high'], accident_probability['medium'])
rule244 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule245 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule246 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule247 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule248 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule249 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule250 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule251 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule252 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])

rule253 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule254 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule255 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule256 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule257 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule258 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule259 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule260 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule261 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule262 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule263 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule264 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule265 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule266 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule267 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule268 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule269 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule270 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule271 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule272 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule273 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule274 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule275 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule276 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule277 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule278 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule279 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule280 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule281 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule282 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule283 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule284 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule285 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['medium']&rainfall['high'], accident_probability['high'])
rule286 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule287 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule288 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])

rule289 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule290 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule291 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule292 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule293 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule294 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule295 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule296 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule297 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule298 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule299 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule300 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule301 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule302 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule303 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['high'], accident_probability['high'])
rule304 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule305 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule306 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule307 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule308 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule309 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule310 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule311 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule312 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['medium']&rainfall['high'], accident_probability['high'])
rule313 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule314 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule315 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule316 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule317 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule318 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule319 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule320 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule321 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['medium']&rainfall['high'], accident_probability['high'])
rule322 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule323 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule324 = ctrl.Rule(age_of_driver['aged']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])



rule325 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule326 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule327 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule328 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule329 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['medium']&rainfall['medium'], accident_probability['low'])
rule330 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule331 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule332 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule333 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['morning']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule334 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule335 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule336 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule337 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule338 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule339 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['high'], accident_probability['high'])
rule340 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule341 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule342 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule343 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule344 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule345 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule346 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule347 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['medium']&rainfall['medium'], accident_probability['low'])
rule348 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule349 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule350 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule351 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['evening']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule352 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule353 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule354 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule355 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule356 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule357 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule358 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule359 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule360 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['new']&time_of_day['night']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])

rule361 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule362 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule363 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule364 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule365 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule366 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['medium']&rainfall['high'], accident_probability['high'])
rule367 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule368 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule369 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['morning']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule370 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule371 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule372 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule373 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule374 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule375 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['high'], accident_probability['high'])
rule376 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule377 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule378 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule379 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule380 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule381 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule382 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule383 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule384 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['medium']&rainfall['high'], accident_probability['high'])
rule385 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule386 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule387 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['evening']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule388 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule389 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule390 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule391 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule392 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule393 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['medium']&rainfall['high'], accident_probability['high'])
rule394 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule395 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule396 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['moderate']&time_of_day['night']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])

rule397 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule398 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule399 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule400 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule401 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule402 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule403 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule404 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['high']&rainfall['medium'], accident_probability['medium'])
rule405 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['morning']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule406 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule407 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule408 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule409 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule410 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule411 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['medium']&rainfall['high'], accident_probability['high'])
rule412 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule413 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule414 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['afternoon']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule415 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule416 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule417 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['low']&rainfall['high'], accident_probability['low'])
rule418 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule419 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule420 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['medium']&rainfall['high'], accident_probability['medium'])
rule421 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['high']&rainfall['low'], accident_probability['low'])
rule422 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule423 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['evening']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])
rule424 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['low']&rainfall['low'], accident_probability['low'])
rule425 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['low']&rainfall['medium'], accident_probability['low'])
rule426 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['low']&rainfall['high'], accident_probability['medium'])
rule427 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['medium']&rainfall['low'], accident_probability['low'])
rule428 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['medium']&rainfall['medium'], accident_probability['medium'])
rule429 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['medium']&rainfall['high'], accident_probability['high'])
rule430 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['high']&rainfall['low'], accident_probability['medium'])
rule431 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['high']&rainfall['medium'], accident_probability['high'])
rule432 = ctrl.Rule(age_of_driver['senior']&age_of_vehicle['old']&time_of_day['night']&num_accident_locations['high']&rainfall['high'], accident_probability['high'])

print("7")


rules = [rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9, rule10, rule11, rule12, rule13, rule14, rule15, 
            rule16, rule17, rule18, rule19, rule20, rule21, rule22, rule23, rule24, rule25, rule26, rule27, rule28, rule29, rule30,
            rule31, rule32, rule33, rule34, rule35, rule36, rule37, rule38, rule39, rule40, rule41, rule42, rule43, rule44, rule45,
            rule46, rule47, rule48, rule49, rule50, rule51, rule52, rule53, rule54, rule55, rule56, rule57, rule58, rule59, rule60,
            rule61, rule62, rule63, rule64, rule65, rule66, rule67, rule68, rule69, rule70, rule71, rule72, rule73, rule74, rule75,
            rule76, rule77, rule78, rule79, rule80, rule81, rule82, rule83, rule84, rule85, rule86, rule87, rule88, rule89, rule90,
            rule91, rule92, rule93, rule94, rule95, rule96, rule97, rule98, rule99, rule100, rule101, rule102, rule103, rule104, 
            rule105, rule106, rule107, rule108, rule109, rule110, rule111, rule112, rule113, rule114, rule115, rule116, rule117, 
            rule118, rule119, rule120, rule121, rule122, rule123, rule124, rule125, rule126, rule127, rule128, rule129, rule130, 
            rule131, rule132, rule133, rule134, rule135, rule136, rule137, rule138, rule139, rule140, rule141, rule142, rule143, 
            rule144, rule145, rule146, rule147, rule148, rule149, rule150, rule151, rule152, rule153, rule154, rule155, rule156, 
            rule157, rule158, rule159, rule160, rule161, rule162, rule163, rule164, rule165, rule166, rule167, rule168, rule169, 
            rule170, rule171, rule172, rule173, rule174, rule175, rule176, rule177, rule178, rule179, rule180, rule181, rule182, 
            rule183, rule184, rule185, rule186, rule187, rule188, rule189, rule190, rule191, rule192, rule193, rule194, rule195, 
            rule196, rule197, rule198, rule199, rule200, rule201, rule202, rule203, rule204, rule205, rule206, rule207, rule208, 
            rule209, rule210, rule211, rule212, rule213, rule214, rule215, rule216, rule217, rule218, rule219, rule220, rule221, 
            rule222, rule223, rule224, rule225, rule226, rule227, rule228, rule229, rule230, rule231, rule232, rule233, rule234, 
            rule235, rule236, rule237, rule238, rule239, rule240, rule241, rule242, rule243, rule244, rule245, rule246, rule247, 
            rule248, rule249, rule250, rule251, rule252, rule253, rule254, rule255, rule256, rule257, rule258, rule259, rule260, 
            rule261, rule262, rule263, rule264, rule265, rule266, rule267, rule268, rule269, rule270, rule271, rule272, rule273, 
            rule274, rule275, rule276, rule277, rule278, rule279, rule280, rule281, rule282, rule283, rule284, rule285, rule286, 
            rule287, rule288, rule289, rule290, rule291, rule292, rule293, rule294, rule295, rule296, rule297, rule298, rule299, 
            rule300, rule301, rule302, rule303, rule304, rule305, rule306, rule307, rule308, rule309, rule310, rule311, rule312, 
            rule313, rule314, rule315, rule316, rule317, rule318, rule319, rule320, rule321, rule322, rule323, rule324, rule325, 
            rule326, rule327, rule328, rule329, rule330, rule331, rule332, rule333, rule334, rule335, rule336, rule337, rule338, 
            rule339, rule340, rule341, rule342, rule343, rule344, rule345, rule346, rule347, rule348, rule349, rule350, rule351, 
            rule352, rule353, rule354, rule355, rule356, rule357, rule358, rule359, rule360, rule361, rule362, rule363, rule364, 
            rule365, rule366, rule367, rule368, rule369, rule370, rule371, rule372, rule373, rule374, rule375, rule376, rule377, 
            rule378, rule379, rule380, rule381, rule382, rule383, rule384, rule385, rule386, rule387, rule388, rule389, rule390, 
            rule391, rule392, rule393, rule394, rule395, rule396, rule397, rule398, rule399, rule400, rule401, rule402, rule403, 
            rule404, rule405, rule406, rule407, rule408, rule409, rule410, rule411, rule412, rule413, rule414, rule415, rule416, 
            rule417, rule418, rule419, rule420, rule421, rule422, rule423, rule424, rule425, rule426, rule427, rule428, rule429, 
            rule430, rule431, rule432
]

print("8")
accident_ctrl = ctrl.ControlSystem(rules)
accident_sim = ctrl.ControlSystemSimulation(accident_ctrl)
print("9")

# Save the control system object
with open('accident_ctrl.pkl', 'wb') as f:
    pickle.dump(accident_ctrl, f)

# Optionally, save the simulation object too
with open('accident_sim.pkl', 'wb') as f:
    pickle.dump(accident_sim, f)